apiVersion: apps/v1
kind: Deployment
metadata:
  name: gem-admin
spec:
  selector:
    matchLabels:
      app: gem-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: gem-admin
    spec:
      containers:
        - name: gem-admin
          image: maples/gem-admin
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: gem-admin
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
  selector:
    app: gem-admin
  type: NodePort